<?php
// Array of devices supported by iOS 8.
$all_devices = array(
	"iPhone4,1" => array(
		"cpu" => "Apple A5 @ 800 MHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2 @ 200 MHz",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "3.7 V 5.3 W·h (1,432 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone5,1" => array(
		"cpu" => "Apple A6 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX543MP3 @ 266 MHz",
		"gpu_cores" => 3,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.45 W·h (1,440 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone5,2" => array(
		"cpu" => "Apple A6 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX543MP3 @ 266 MHz",
		"gpu_cores" => 3,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.45 W·h (1,440 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone5,3" => array(
		"cpu" => "Apple A6 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX543MP3 @ 266 MHz",
		"gpu_cores" => 3,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.73 W·h (1,507 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone5,4" => array(
		"cpu" => "Apple A6 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX543MP3 @ 266 MHz",
		"gpu_cores" => 3,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.73 W·h (1,507 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone6,1" => array(
		"cpu" => "Apple A7 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.96 W·h (1,570 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone6,2" => array(
		"cpu" => "Apple A7 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.8 V 5.96 W·h (1,570 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone7,1" => array(
		"cpu" => "Apple A8 @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6450",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n/ac",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.82 V 6.91 W·h (1,810 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPhone7,2" => array(
		"cpu" => "Apple A8 @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6450",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n/ac",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "3.82 V 11.1 W·h (2,915 mA·h)",
		"camera_mp" => "8 MP",
		"response" => true,
	),
	"iPad2,1" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "2.1+EDR",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "~0.92 MP",
		"response" => true,
	),
	"iPad2,2" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "2.1+EDR",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "~0.92 MP",
		"response" => true,
	),
	"iPad2,3" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "2.1+EDR",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "~0.92 MP",
		"response" => true,
	),
	"iPad2,4" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "2.1+EDR",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "~0.92 MP",
		"response" => true,
	),
	"iPad2,5" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad2,6" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad2,7" => array(
		"cpu" => "Apple A5 @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,1" => array(
		"cpu" => "Apple A5X @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,2" => array(
		"cpu" => "Apple A5X @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,3" => array(
		"cpu" => "Apple A5X @ 1 GHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,4" => array(
		"cpu" => "Apple A6X @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX554MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,5" => array(
		"cpu" => "Apple A6X @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX554MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad3,6" => array(
		"cpu" => "Apple A6X @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv7s 32-bit",
		"gpu" => "PowerVR SGX554MP4",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Micro-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,1" => array(
		"cpu" => "Apple A7 @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,2" => array(
		"cpu" => "Apple A7 @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,3" => array(
		"cpu" => "Apple A7 @ 1.4 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,4" => array(
		"cpu" => "Apple A7 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,5" => array(
		"cpu" => "Apple A7 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPad4,6" => array(
		"cpu" => "Apple A7 @ 1.3 GHz",
		"cpu_cores" => 2,
		"arch" => "ARMv8-A 64-bit",
		"gpu" => "PowerVR G6430",
		"gpu_cores" => 4,
		"memory" => "1 GB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "Nano-SIM",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"iPod5,1" => array(
		"cpu" => "Apple A5 @ 800 MHz",
		"cpu_cores" => 2,
		"arch" => "ARM Cortex A9 32-bit",
		"gpu" => "PowerVR SGX543MP2",
		"gpu_cores" => 2,
		"memory" => "512 MB",
		"wifi" => "802.11 a/b/g/n",
		"bluetooth" => "4.0",
		"sim" => "N/A",
		"power" => "---",
		"camera_mp" => "5 MP",
		"response" => true,
	),
	"unknown" => array(
		"cpu" => "Unknown",
		"cpu_cores" => 0,
		"arch" => "ARM",
		"gpu" => "Unknown",
		"gpu_cores" => 0,
		"memory" => "Unknown",
		"wifi" => "Unknown",
		"bluetooth" => "Unknown",
		"sim" => "Unknown",
		"power" => "Unknown",
		"camera_mp" => "Unknown",
		"response" => false,
	),
);

if (isset($_GET["q"])) {
	$query = $_GET["q"];
	if ($query == "hash") {
		$json_hash = hash('sha256', json_encode($device_info));
		$response = array(
			"checksum" => $json_hash,
			"response" => "true",
		);
		echo '<pre>'.json_encode($response, JSON_PRETTY_PRINT).'</pre>';
	}
	else if ($query == "updates") {
		$app_version = array(
			0 => "v1.0",
		);
		echo '<pre>'.json_encode($app_version, JSON_PRETTY_PRINT).'</pre>';
	}
}
else {
	echo '<pre>'.json_encode($all_devices, JSON_PRETTY_PRINT).'</pre>';
}
?>